### ISSUE TITLE
domain mapping failed

### ISSUE THREAD

**Issue by bind-almir** [smallwins/begin-issues#9] opened 2018-09-25 21:35 UTC
**Expected behavior**
Map my existing domain name to Begin app

**Description of bug**
In the first domain mapping step, after I enter my domain names for production and staging environment, I get the following error message:

> TypeError: Cannot read property 'account' of undefined
> TypeError: Cannot read property 'account' of undefined
>     at requestCertificate (/var/task/node_modules/@architect/shared/_request-certificate.js:7:27)
>     at Object.request (/var/task/index.js:33:3)
>     at Object._iter (/var/task/node_modules/@architect/functions/src/http/_request.js:73:12)
>     at Object.create (/var/task/index.js:25:5)
>     at Object._iter (/var/task/node_modules/@architect/functions/src/http/_request.js:73:12)
>     at done (/var/task/node_modules/@architect/shared/middleware/auth.js:28:11)
>     at Response._get (/var/task/node_modules/@architect/data/_init.js:36:14)
>     at Request. (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
>     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Go to Domain section 
2. Fill the form for production and staging domain name
3. Click on the Generate SSL certificates button

**Desktop**
 - OS: Ubuntu 17.10
 - Browser: Chrome version 66.0.3359.139 (Official Build) (64-bit)

**Comment by ryanblock** [comment] 2018-09-25 21:43
@bind-almir oy, that sucks. We're looking into it, please stand by!

**Comment by kristoferjoseph** [comment] 2018-09-25 23:11
@bind-almir pushed a fix, please give mapping your domain another go! 🤗

**Comment by ryanblock** [comment] 2018-09-26 15:12
@bind-almir, glad we got that fixed! Sorry about that.

Is the domain you're using in this case already being used with AWS Certificate Manager in your AWS account?

If so that may be what's preventing things from working as it would conflict between AWS accounts, but it's hard to say without digging into this a bit further – and that will probably require some information that you probably don't want here in a public GitHub issue.

I'm going to open a private support issue on your behalf with the email we have on file and we'll go from there!

**Comment by bind-almir** [comment] 2018-09-28 08:56
Hello again :)

Thank you very much for your support. I am sorry that I am re-opening the issue. I feel it's convenient to continue on the same thread.

Production and staging domains are verified, now after I click on the button "Create domain distribution", step 3 throws an error: 

> TypeError: Cannot read property 'appID' of undefined
> TypeError: Cannot read property 'appID' of undefined
>     at createCloudFrontDistribution (/var/task/node_modules/@architect/shared/_create-cloudfront-distributions.js:26:26)
>     at Object.create (/var/task/index.js:12:5)
>     at Object._iter (/var/task/node_modules/@architect/functions/src/http/_request.js:73:12)
>     at done (/var/task/node_modules/@architect/shared/middleware/auth.js:28:11)
>     at Response._get (/var/task/node_modules/@architect/data/_init.js:36:14)
>     at Request. (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
>     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
>     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)

**Comment by ryanblock** [comment] 2018-09-28 15:28
Hey there, this is the right spot – will reopen and look into it! Sorry you've hit every branch on the way down with this one.

**Comment by ryanblock** [comment] 2018-09-28 17:04
Ok, I just pushed a fix for this. When we released this feature it was working, but there were a couple of regressions, and you caught both of them. Which means the good news is: as far as I can tell, there are no more places for us to break you in this flow! Heh.

Again, thank you very much for your patience.

I tested the flow end to end before releasing to production and it worked perfectly; the fix is now live, and I'm testing it again in prod, too. (Since it's DNS a full test pass on this can take 10-60 minutes, so I'll check back if I notice anything is amiss.)

To put a bow on this: just go back to the domains page, hit that `Create domain distribution` button one more time, and you should be good to go to complete your domain setup!

**Closed by ryanblock** 2018-09-28 17:04 UTC
Labels: bug
